export const AWS_ACCESS_KEY_ID = "AKIAYXCXQMBAIQ5HDZVI"
export const AWS_SECRET_ACCCESS_KEY = "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"

// process.env.AWS_ACCESS_KEY_ID = "AKIAYXCXQMBAIBKDX2QY"
// process.env.AWS_SECRET_ACCCESS_KEY = "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"
