// process.env.AWS_ACCESS_KEY_ID = "AKIAYXCXQMBACR6H7NVC";
process.env.AWS_ACCESS_KEY_ID = "AKIAYXCXQMBABXPH2T4R";
// process.env.AWS_SECRET_ACCCESS_KEY = "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";
process.env.AWS_SECRET_ACCCESS_KEY = "Ei2T8+QHZxmJ5lIn4drwnt6+s74fLyxzq8bDKRfM";
