// process.env.AWS_ACCESS_KEY_ID = "AKIAYXCXQMBACR6H7NVC";
process.env.AWS_ACCESS_KEY_ID = "AKIAYXCXQMBADGA5BLFH";
// process.env.AWS_SECRET_ACCCESS_KEY = "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";
process.env.AWS_SECRET_ACCCESS_KEY = "ySJyPBrSJ06T+At9iWxvriIMiSufYED8i8ggLMQi";
